//UI Constants
UIConstants.LASER_WIDTH = 8
UIConstants.AIMER_WIDTH = 8
UIConstants.TANK_FEATHER_COUNT = 0
UIConstants.TANK_FEATHER_POOL_SIZE = 0
UIConstants.MAX_SCORE_FRAGMENTS_PER_EXPLOSION = 0
UIConstants.MIN_SCORE_FRAGMENTS_PER_LETTER = 0
UIConstants.EXPLOSION_FRAGMENT_MIN_LIFETIME = 10
UIConstants.EXPLOSION_FRAGMENT_MAX_LIFETIME = 12
UIConstants.TANK_ICON_OUTLINE_WIDTH = 1.2
UIConstants.GAME_ICON_WIDTH /= 1.3;
UIConstants.GAME_ICON_HEIGHT /= 1.3;
UIConstants.GATLING_GUN_MIN_ANIMATION_SPEED = 6
UIConstants.GATLING_GUN_ANIMATION_SPEED_RANGE = 24
UIConstants.SCORE_STROKE_WIDTH = 0
